name: Test Java Compilation

on:
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up the latest JDK using Temurin (AdoptOpenJDK's successor)
    - name: Set up latest JDK
      uses: actions/setup-java@v3
      with:
        java-version: 22  # This will automatically pick the latest stable version of Java
        distribution: 'temurin' # Using the Temurin distribution (AdoptOpenJDK's successor)

        # Compile Java code
    - name: Compile all Java files
      run: |
        javac -d out java_code/*.java


    - name: Run all Java files
      run: |
        for class_file in out/java/*.class; do
          class_name=$(basename "$class_file" .class)
          if javap -public "$class_file" | grep -q 'public static void main'; then
            java -cp out java_code.$class_name
          fi
        done