name: Test Java Compilation

on:
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up the latest JDK using Temurin (AdoptOpenJDK's successor)
    - name: Set up latest JDK
      uses: actions/setup-java@v3
      with:
        java-version: 22  # This will automatically pick the latest stable version of Java
        distribution: 'temurin' # Using the Temurin distribution (AdoptOpenJDK's successor)

        # Compile Java code
    - name: Compile Java code
      run: |
        # java java_code/*.java
        for class_files in javacode/*.java; do
          class_name = ${basename "class_file" .java}
          echo "Executing $class_name"
          echo
          java Test1020.java_code.$class_files
        done
